package exception;

import java.sql.Connection;
import java.sql.SQLException;

public class Sample {
	public static void main(String[] args) {
		try{
			int x=10;
		
		int y=0;
		int z=x/y;// logicaal issue
		int [] nums = new int[5];
		nums[4]=200;
		Connection con=DirverManager.getConnection("", """, "");
	}
	catch (ArithmeticException e) {
		System.out.println(e.getMessage());
		System.out.println("we can not div a num by zero");
		
	}catch(ArrayIndexOutOfBoundsException e) {
		System.out.println(e.getMessage());
		System.out.println("we can not place elements out of array's boundries");
		
	}catch(SQLException e) {
		System.out.println(e.getMessage());
		System.out.println("could not connect to the database");
	}

	System.out.println(e.getMessage());
		
	System.out.println("something went wrong");
	

	}
}

